/**
 * V6.5 Phase 7: AT Write Result Store
 *
 * Correlates canonical write submissions with their projected AT repo results
 * (URI + CID) so that XRPC write routes can return protocol-correct responses.
 *
 * Problem: XRPC write procedures (createRecord, putRecord) must return the
 * resulting AT URI and CID synchronously, but writes flow through canonical
 * Tier 1 first, then drive AT projection asynchronously.
 *
 * Solution: a pub/sub result store keyed by clientMutationId.
 *   1. XRPC route generates a clientMutationId
 *   2. CanonicalClientWriteService propagates it through the canonical event
 *   3. AT projection path calls publishResult() when the commit is built
 *   4. XRPC route calls waitForResult(), which resolves when step 3 happens
 *
 * This module provides both an in-memory implementation (tests/single process)
 * and a Redis-backed implementation (durable, multi-instance).
 */

import type Redis from 'ioredis';
import type { AtWriteResult } from './AtWriteTypes.js';

// ---------------------------------------------------------------------------
// Interface
// ---------------------------------------------------------------------------

export interface AtWriteResultStore {
  /**
   * Wait for the projected AT result of a canonical write.
   *
   * @param clientMutationId  ID generated by the XRPC route
   * @param timeoutMs         How long to wait before returning null
   * @returns                 The projected URI+CID, or null on timeout
   */
  waitForResult(
    clientMutationId: string,
    timeoutMs: number
  ): Promise<AtWriteResult | null>;

  /**
   * Publish the AT result of a completed projection commit.
   * Called by the AT projection path after a new commit is built.
   */
  publishResult(
    clientMutationId: string,
    result: AtWriteResult
  ): Promise<void>;

  /**
   * Release all resources held by this store (subscriber connection, etc.).
   * Safe to call multiple times.
   */
  close?(): Promise<void>;
}

// ---------------------------------------------------------------------------
// Redis-backed implementation (durable, multi-instance)
// ---------------------------------------------------------------------------

export interface RedisAtWriteResultStoreOptions {
  redis: Redis;
  /** Key prefix used for persisted results. */
  keyPrefix?: string;
  /** Pub/sub channel prefix used for cross-instance waiter wakeups. */
  channelPrefix?: string;
  /** TTL for persisted write results, in seconds. */
  resultTtlSec?: number;
}

interface RedisPendingEntry {
  resolve: (result: AtWriteResult | null) => void;
  timeoutHandle: ReturnType<typeof setTimeout>;
}

export class RedisAtWriteResultStore implements AtWriteResultStore {
  private readonly redis: Redis;
  private readonly keyPrefix: string;
  private readonly channelPrefix: string;
  private readonly resultTtlSec: number;

  private readonly pending = new Map<string, RedisPendingEntry>();

  private subscriber: Redis | null = null;
  private subscribeReady: Promise<void> | null = null;
  private closed = false;

  constructor(options: RedisAtWriteResultStoreOptions) {
    this.redis = options.redis;
    this.keyPrefix = options.keyPrefix ?? 'at:write-result';
    this.channelPrefix = options.channelPrefix ?? 'at:write-result:ch';
    this.resultTtlSec = options.resultTtlSec ?? 120;
  }

  async waitForResult(
    clientMutationId: string,
    timeoutMs: number
  ): Promise<AtWriteResult | null> {
    const existing = await this.readPersistedResult(clientMutationId);
    if (existing) return existing;

    // Best-effort subscriber setup — degrade to timeout-only if unavailable.
    try {
      await this.ensureSubscriber();
    } catch {
      // Subscriber unavailable; wait by polling Redis once after the result key
      // should have been written, then fall through to the timeout path.
    }

    return new Promise<AtWriteResult | null>((resolve) => {
      const timeoutHandle = setTimeout(() => {
        this.pending.delete(clientMutationId);
        resolve(null);
      }, timeoutMs);

      this.pending.set(clientMutationId, { resolve, timeoutHandle });

      // Re-check after waiter registration to close publish-between race.
      void this.readPersistedResult(clientMutationId)
        .then((result) => {
          if (result) this.resolvePending(clientMutationId, result);
        })
        .catch(() => {
          // The timeout path remains the fallback if Redis read fails.
        });
    });
  }

  async publishResult(
    clientMutationId: string,
    result: AtWriteResult
  ): Promise<void> {
    // Resolve same-process waiters immediately.
    this.resolvePending(clientMutationId, result);

    const payload = JSON.stringify(result);
    const resultKey = this.resultKey(clientMutationId);

    await this.redis.set(resultKey, payload, 'EX', this.resultTtlSec);
    await this.redis.publish(this.channelName(clientMutationId), payload);
  }

  private async ensureSubscriber(): Promise<void> {
    if (this.closed) throw new Error('RedisAtWriteResultStore is closed');

    if (this.subscribeReady) {
      await this.subscribeReady;
      return;
    }

    const attempt = (async () => {
      const sub = this.redis.duplicate();
      this.subscriber = sub;

      sub.on('pmessage', (_pattern: string, channel: string, message: string) => {
        const mutationId = this.mutationIdFromChannel(channel);
        if (!mutationId) return;

        let parsed: AtWriteResult | null = null;
        try {
          parsed = JSON.parse(message) as AtWriteResult;
        } catch {
          return;
        }

        this.resolvePending(mutationId, parsed);
      });

      await sub.psubscribe(`${this.channelPrefix}:*`);
    })();

    // Cache only on success; on failure reset so the next call can retry.
    this.subscribeReady = attempt.catch((err) => {
      this.subscribeReady = null;
      this.subscriber = null;
      throw err;
    });

    await this.subscribeReady;
  }

  async close(): Promise<void> {
    if (this.closed) return;
    this.closed = true;

    // Reject all pending waiters immediately rather than waiting for timeout.
    for (const [id, entry] of this.pending) {
      clearTimeout(entry.timeoutHandle);
      entry.resolve(null);
      this.pending.delete(id);
    }

    if (this.subscriber) {
      try {
        await this.subscriber.quit();
      } catch {
        this.subscriber.disconnect();
      }
      this.subscriber = null;
    }

    this.subscribeReady = null;
  }

  private async readPersistedResult(
    clientMutationId: string
  ): Promise<AtWriteResult | null> {
    const payload = await this.redis.get(this.resultKey(clientMutationId));
    if (!payload) return null;

    try {
      return JSON.parse(payload) as AtWriteResult;
    } catch {
      return null;
    }
  }

  private resolvePending(clientMutationId: string, result: AtWriteResult): void {
    const pendingEntry = this.pending.get(clientMutationId);
    if (!pendingEntry) return;

    clearTimeout(pendingEntry.timeoutHandle);
    this.pending.delete(clientMutationId);
    pendingEntry.resolve(result);
  }

  private resultKey(clientMutationId: string): string {
    return `${this.keyPrefix}:${clientMutationId}`;
  }

  private channelName(clientMutationId: string): string {
    return `${this.channelPrefix}:${clientMutationId}`;
  }

  private mutationIdFromChannel(channel: string): string | null {
    const prefix = `${this.channelPrefix}:`;
    if (!channel.startsWith(prefix)) return null;
    return channel.slice(prefix.length) || null;
  }

  /** Visible for testing. */
  get pendingCount(): number {
    return this.pending.size;
  }
}

// ---------------------------------------------------------------------------
// In-memory implementation (single-process)
// ---------------------------------------------------------------------------

interface PendingEntry {
  resolve: (result: AtWriteResult) => void;
  timeoutHandle: ReturnType<typeof setTimeout>;
}

export class InMemoryAtWriteResultStore implements AtWriteResultStore {
  /** Waiting XRPC routes: mutationId → resolve callback */
  private readonly pending = new Map<string, PendingEntry>();

  /**
   * Results that arrived before a waiter registered (projection can win the
   * race if the canonical write + projection is faster than the XRPC await).
   */
  private readonly earlyResults = new Map<string, AtWriteResult>();

  /** How long to retain an early result before discarding (default 30s). */
  private readonly earlyResultTtlMs: number;

  constructor(options?: { earlyResultTtlMs?: number }) {
    this.earlyResultTtlMs = options?.earlyResultTtlMs ?? 30_000;
  }

  async waitForResult(
    clientMutationId: string,
    timeoutMs: number
  ): Promise<AtWriteResult | null> {
    // Fast path: projection already published before we started waiting
    const early = this.earlyResults.get(clientMutationId);
    if (early) {
      this.earlyResults.delete(clientMutationId);
      return early;
    }

    return new Promise<AtWriteResult | null>((resolve) => {
      const timeoutHandle = setTimeout(() => {
        this.pending.delete(clientMutationId);
        resolve(null);
      }, timeoutMs);

      this.pending.set(clientMutationId, { resolve, timeoutHandle });
    });
  }

  async publishResult(
    clientMutationId: string,
    result: AtWriteResult
  ): Promise<void> {
    const entry = this.pending.get(clientMutationId);
    if (entry) {
      clearTimeout(entry.timeoutHandle);
      this.pending.delete(clientMutationId);
      entry.resolve(result);
      return;
    }

    // No waiter yet — park the result so waitForResult can pick it up
    this.earlyResults.set(clientMutationId, result);

    // Auto-expire to prevent memory leaks from abandoned mutations
    setTimeout(() => {
      this.earlyResults.delete(clientMutationId);
    }, this.earlyResultTtlMs);
  }

  /** Visible for testing: number of open waiters */
  get pendingCount(): number {
    return this.pending.size;
  }

  /** Visible for testing: number of early results held */
  get earlyResultCount(): number {
    return this.earlyResults.size;
  }
}
