FROM node:22-bookworm-slim

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --legacy-peer-deps

COPY src ./src
COPY interop ./interop
COPY scripts ./scripts
COPY tsconfig.json ./

CMD ["sleep", "infinity"]
