FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install --legacy-peer-deps

COPY src ./src
COPY interop ./interop
COPY scripts ./scripts
COPY tsconfig.json ./

CMD ["sleep", "infinity"]
